name: Test PyPI Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0b1)'
        required: true
        type: string

permissions:
  contents: write
  id-token: write

jobs:
  validate:
    name: Validate Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate version format
      run: |
        VERSION="${{ github.event.inputs.version }}"
        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(b[0-9]+)?$ ]]; then
          echo "Error: Invalid version format. Use semantic versioning (e.g., 0.1.0 or 0.1.0b1)"
          exit 1
        fi
        
  build-for-testpypi:
    name: Build for Test PyPI
    needs: validate
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Update version
      run: |
        VERSION="${{ github.event.inputs.version }}"
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" pyproject.toml
        echo "Updated version to $VERSION"
        
    - name: Prepare for Test PyPI (remove local dependencies)
      run: |
        python - << 'SCRIPT'
        import re
        with open('pyproject.toml', 'r') as f:
            content = f.read()
        # Remove tool.uv.sources
        content = re.sub(r'\[tool\.uv\.sources\].*?(?=\[|$)', '', content, flags=re.DOTALL)
        # Add notice about missing dependencies
        content = re.sub(
            r'(description = "[^"]*")',
            r'\1\n# NOTE: Requires bedrock-agentcore, boto3, and botocore wheels installed separately',
            content
        )
        with open('pyproject.toml', 'w') as f:
            f.write(content)
        SCRIPT
        
    - name: Build distribution
      run: python -m build
      
    - name: Check distribution
      run: |
        twine check dist/*
        ls -la dist/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: testpypi-dist
        path: dist/
        
  publish-testpypi:
    name: Publish to Test PyPI
    needs: build-for-testpypi
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/bedrock-agentcore-starter-toolkit
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: testpypi-dist
        path: dist/
        
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip-existing: true
        
    - name: Create installation instructions
      run: |
        VERSION="${{ github.event.inputs.version }}"
        cat > test-pypi-instructions.md << INSTRUCTIONS
        # Test PyPI Installation Instructions
        
        Package published: bedrock-agentcore-starter-toolkit==$VERSION
        
        ## Installation Steps:
        
        1. First install the private dependencies from wheelhouse:
           \`\`\`bash
           pip install ./wheelhouse/botocore-*.whl
           pip install ./wheelhouse/boto3-*.whl
           pip install ./wheelhouse/bedrock_agentcore-*.whl
           \`\`\`
        
        2. Then install from Test PyPI:
           \`\`\`bash
           pip install -i https://test.pypi.org/simple/ bedrock-agentcore-starter-toolkit==$VERSION
           \`\`\`
        
        Note: Direct installation will fail due to missing dependencies.
        INSTRUCTIONS
        
        echo "::notice file=test-pypi-instructions.md::Test PyPI installation instructions created"
