name: Test PyPI Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor

permissions:
  contents: write
  id-token: write

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Get current version
      id: version
      run: |
        CURRENT_VERSION=$(grep -oP 'version = "\K[^"]+' pyproject.toml)
        echo "Current version: $CURRENT_VERSION"
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
        
    - name: Update version
      run: |
        python scripts/bump-version.py ${{ github.event.inputs.version_bump }}
        NEW_VERSION=$(grep -oP 'version = "\K[^"]+' pyproject.toml)
        echo "New version: $NEW_VERSION"
        
  test-and-build:
    name: Test and Build
    needs: prepare-release
    uses: ./.github/workflows/ci.yml
    
  publish-test-pypi:
    name: Publish to Test PyPI
    needs: [prepare-release, test-and-build]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/bedrock-agentcore-starter-toolkit
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-packages
        path: dist/
        
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        skip-existing: true
        
    - name: Wait for package availability
      run: sleep 60
      
    - name: Test installation from Test PyPI
      run: |
        python -m venv test-install
        source test-install/bin/activate
        pip install --index-url https://test.pypi.org/simple/ \
                    --extra-index-url https://pypi.org/simple/ \
                    bedrock-agentcore-starter-toolkit==${{ needs.prepare-release.outputs.version }}
        python -c "from bedrock_agentcore_starter_toolkit import Runtime; print('✓ Test PyPI install successful')"
        agentcore --version
